<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJJWIjad\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJJWIjad/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJJWIjad.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJJWIjad\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJJWIjad\appAppKernelProdContainer([
    'container.build_hash' => 'JJWIjad',
    'container.build_id' => '926810f3',
    'container.build_time' => 1721125967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJJWIjad');
