<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM8SPRLJ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM8SPRLJ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerM8SPRLJ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerM8SPRLJ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerM8SPRLJ\appAppKernelProdContainer([
    'container.build_hash' => 'M8SPRLJ',
    'container.build_id' => 'c953a930',
    'container.build_time' => 1720446857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM8SPRLJ');
